CREATE TABLE [dbo].[COMPUESTO_MATERIAL_PESOS](
	[IDPRODUCTOSMATERIAL] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](50) NULL,
	[RESINA1] [varchar](50) NULL,
	[PESORESINA1] [money] NULL,
	[RESINA2] [varchar](50) NULL,
	[PESORESINA2] [money] NULL,
	[RESINA3] [varchar](50) NULL,
	[PESORESINA3] [money] NULL,
	[RESINA4] [varchar](50) NULL,
	[PESORESINA4] [money] NULL,
	[RESINA5] [varchar](50) NULL,
	[PESORESINA5] [money] NULL,
	[PIGMENTO1] [varchar](50) NULL,
	[PESOPIGMENTO1] [money] NULL,
	[PIGMENTO2] [varchar](50) NULL,
	[PESOPIGMENTO2] [money] NULL,
	[PIGMENTO3] [varchar](50) NULL,
	[PESOPIGMENTO3] [money] NULL,
	[PIGMENTO4] [varchar](50) NULL,
	[PESOPIGMENTO4] [money] NULL,
	[PIGMENTO5] [varchar](50) NULL,
	[PESOPIGMENTO5] [money] NULL,
 CONSTRAINT [PK_COMPUESTO_MATERIAL_PESOS] PRIMARY KEY CLUSTERED 
(
	[IDPRODUCTOSMATERIAL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
